sudo: required
dist: xenial
language: node_js
node_js:
  - "10"

services:
  - docker

env:
  global:
    - GH_REPO_NAME: chromium-screenshot
    - GH_REPO_REF: github.com/christopher-evans/$GH_REPO_NAME.git
    - MKDOCS_OUTPUT: site

before_install:
  - docker build -t chromium-screenshot-test -f Dockerfile.test .

script:
  - docker run chromium-screenshot-test /bin/sh -c "npm test"
  - docker run chromium-screenshot-test /bin/sh -c "npm run lint"

after_success:
  - npm run coverage
  - chmod +x bin/travis-docs.sh
  - ./bin/travis-docs.sh $MKDOCS_OUTPUT $GH_REPO_NAME $GH_REPO_REF

notifications:
  email: false
