sudo: required
dist: xenial

services:
  - docker

env:
  global:
    - GH_REPO_NAME: chromium-screenshot
    - GH_REPO_REF: github.com/christopher-evans/$GH_REPO_NAME.git
    - MKDOCS_OUTPUT: site

before_install:
  - docker build -t chromium-screenshot-test -f Dockerfile.test .

script:
  - docker run chromium-screenshot-test /bin/sh -c "npm test"
  - docker run chromium-screenshot-test /bin/sh -c "npm run lint"

after_success:
  - docker run chromium-screenshot-test /bin/sh -c "chmod a+x bin/travis-docs.sh"
  - docker run chromium-screenshot-test /bin/sh -c "bin/travis-docs.sh ${MKDOCS_OUTPUT} ${GH_REPO_NAME} ${GH_REPO_REF} ${GH_REPO_TOKEN}"
  - docker run chromium-screenshot-test /bin/sh -c "npm -v"
  - docker run chromium-screenshot-test /bin/sh -c "npm run coverage"

notifications:
  email: false
