sudo: false
language: node_js

env:
  global:
    - GH_REPO_NAME: chromium-screenshot
    - GH_ROOT: github.com/christopher-evans
    - GH_REPO_REF: $GH_ROOT/$GH_REPO_NAME.git
    - MKDOCS_OUTPUT: site

matrix:
  include:
    - node_js: 11
      env:
      - TEST=true
    - node_js: 10
      env:
      - TEST=true
    - node_js: 9
      env:
      - TEST=true
    - node_js: 8
      env:
      - TEST=true
    - node_js: "stable"
      env:
      - TEST=true
      - TEST_COVERAGE=true
      - BUILD_DOCS=true


install:
  - travis_retry npm install

script:
  - if [[ $TEST == 'true' ]]; then npm test ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then npm run coverage ; fi

after_success:
    - if [[ $BUILD_DOCS == 'true' ]]; then chmod +x bin/travis-docs.sh ; fi
    - if [[ $BUILD_DOCS == 'true' ]]; then ./bin/travis-docs.sh $MKDOCS_OUTPUT $GH_REPO_NAME $GH_REPO_REF ; fi

notifications:
  email: false