sudo: required

services:
  - docker

before_install:
  - docker build -t chromium-screenshot-test -f Dockerfile.test .
  - container_id=$(mktemp)
  - docker run -p 8080:8080 -d chromium-screenshot-test > "${container_id}"

script:
  - docker exec "$(cat ${container_id})" npm test
  - docker exec "$(cat ${container_id})" npm run lint

after_success:
  - docker exec "$(cat ${container_id})" npm run coverage
  - docker exec "$(cat ${container_id})" chmod +x bin/travis-docs.sh
  - docker exec -it "$(cat ${container_id})" bin/travis-docs.sh $GH_REPO_TOKEN $TRAVIS_BUILD_NUMBER $TRAVIS_COMMIT

notifications:
  email: false
